esphome:
  name: bpi-bit
  friendly_name: BPI-BIT

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "fdgfdsgdfsgfdsgfdfd"

#ota:
#  password: "fdgdfasgfdsgfdsgsdgfd"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bpi-Bit Fallback Hotspot"
    password: "fdgfdsgdsfgfds"

captive_portal:

web_server:
  port: 80

#deep_sleep:
#  run_duration: 10s
#  sleep_duration: 5min
  
i2c:
  - id: bus_a
    sda: 21
    scl: 22
    scan: true

sensor:
  - platform: adc
    id: source_sensor
    pin: 34
    update_interval: 5min
  - platform: resistance
    id: resistance_sensor
    sensor: source_sensor
    configuration: UPSTREAM
    resistor: 4.7kOhm
    name: Resistance Sensor
  - platform: ntc
    sensor: resistance_sensor
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    name: NTC Temperature
  - platform: mpu6050
    i2c_id: bus_a
    address: 0x69
    accel_x:
      name: "MPU6050 Accel X"
    accel_y:
      name: "MPU6050 Accel Y"
    accel_z:
      name: "MPU6050 Accel z"
    gyro_x:
      name: "MPU6050 Gyro X"
    gyro_y:
      name: "MPU6050 Gyro Y"
    gyro_z:
      name: "MPU6050 Gyro z"
    temperature:
      name: "MPU6050 Temperature"
  - platform: adc
    id: source_sensor_L
    pin: 36
    update_interval: 5min
  - platform: resistance
    id: resistance_sensor_l
    sensor: source_sensor_L
    configuration: UPSTREAM
    resistor: 510kOhm
    name: Light Sensor L
  - platform: adc
    id: source_sensor_R
    pin: 39
    update_interval: 5min
  - platform: resistance
    id: resistance_sensor_r
    sensor: source_sensor_R
    configuration: UPSTREAM
    resistor: 510kOhm
    name: Light Sensor R

